name: end-reason-figure2-signal-traces
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - nbconvert
  - numpy
  - pandas
  - matplotlib
  - h5py
  - pysam
  - pod5
  - pip:
      - vbz-h5py-plugin
